{{- if and (not .Values.auth.existingSecret) .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-16-dev.authSecretName" . }}
  labels:
    {{- include "postgres-16-dev.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.password | b64enc | quote }}
{{- end }}

