apiVersion: v1
kind: Service
metadata:
  name: { { include "postgres-16-dev.fullname" . } }
  labels: { { - include "postgres-16-dev.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - name: postgres
      port: { { .Values.service.port } }
      targetPort: postgres
      protocol: TCP
  selector: { { - include "postgres-16-dev.selectorLabels" . | nindent 4 } }
